### ISSUE TITLE
Mocking private functions

### ISSUE THREAD

**Issue by emgrasmeder** [zhming0/mock-clj#2]
My team has been using and loving mock-clj for a couple years, but we've been stuck at trying to mock private functions. 
Is there some way to go about this?

```clojure
(ns mock-clj.private)
(defn- private-fn [a]
  "bar")
(ns mock-clj.core-test
  (:require [clojure.test :refer :all]
            [mock-clj.core :refer :all]))

(deftest mock-private-test
  (with-mock [#'mock-clj.private/private-fn "baz"]
    (is (= (#'mock-clj.private/private-fn "x") "baz"))))
```
This throws this following error:  
`CompilerException java.lang.ClassCastException: clojure.lang.Cons cannot be cast to clojure.lang.Symbol`

(Dropping the `#'` before mentions of `mock-clj.private/private-fn` causes `CompilerException java.lang.IllegalStateException: var: mock-clj.private/private-fn is not public` to be thrown)

**Comment by zhming0** [comment]
hi @emilyagras, thanks for using mock-clj. 
I have just published a new version that supports mocking private functions.
Hope it helps.
